### ISSUE TITLE
Linux Mint 19.3 - GUI problem with openjdk11 and openjfx

### ISSUE THREAD

**Issue by Giancarmine** [mauriciojost/olympus-photosync#61] opened 2020-06-03 20:57 UTC
Hi Mauricio,

I Thanks for your work, my Olympus OM-D love your application =)

The app work good from command line, but when i try to star the GUI i have this problem:
```
olympus-photosync --gui
[22:41:41,207 INFO    Starter$] Version: 1.0.0
[22:41:41,710 INFO    Starter$] Loading file configuration: PhotosyncConfig(CameraClientConfig(http,192.168.0.10,80,/DCIM,wlan.*=.*,(.*),(\d+),(\d+),(\d+),(\d+).*,true,None,None),output,Criteria(None,None,None),false,false,false,false,GuiConfig(true,100))
[22:41:41,712 DEBUG        Os$] Detected OS: Linux (property value 'linux')
Exception in thread "main" java.lang.NoClassDefFoundError: javafx/event/EventTarget
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at org.mauritania.photosync.starter.Starter$.startApp(Starter.scala:43)
	at org.mauritania.photosync.starter.Starter$.main(Starter.scala:23)
	at org.mauritania.photosync.starter.Starter.main(Starter.scala)
Caused by: java.lang.ClassNotFoundException: javafx.event.EventTarget
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 30 more
```

I have the openJDK 11.0.7 and the openJFX installed.
```
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment (build 11.0.7+10-post-Ubuntu-2ubuntu218.04)
OpenJDK 64-Bit Server VM (build 11.0.7+10-post-Ubuntu-2ubuntu218.04, mixed mode, sharing)
```

Am I missing somethings?

BR,
-El_Giancar

**Comment by mauriciojost** [comment] 2020-06-04 06:08
Looks like a dupe of #60. It is affecting more people now :) As soon as I get some free time I will try to fix it.

**Closed** 2020-06-15 00:35 UTC
